# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4d7ebb1125f722e350793d33a547ad1d48faffd2ef82ed0109291a0cc8322052aca0956e6d2de00ab55199128230dafa63ea1bb7ec7c3d711af77b76e27b51

test:
  secret_key_base: 22af8387aa71f4af0ce39391c06a808cea6045cea76aaa410501f950d916ade772f5d1158205d7de585b799977c30247557a4b3a2b0a357516a29837e6c85e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
